### ISSUE TITLE
thoughts on preservation of slices

### ISSUE THREAD

**Issue by sigmonsays** [zazab/zhash#9]
I found this library incredibly useful to load and manipulate structures in yaml but it seems to be stripping out lists from the final output when I use WriteHash.  Is it possible to preserve unhandled structures when re-marshaling?

**Comment by sigmonsays** [comment]
example code snippet demonstrating problem

If you do not call conf.Set then junk.items is preserved. However changing a value under junk fails to preserve the items list.

`var test_data = `
junk:
 description: test to see if lists are preserved
 items:
   - 1
   - 2
   - 3
`

func main() {

   conf := zhash.NewHashPtr()
   conf.SetMarshallerFunc(goyaml.Marshal)
   conf.SetUnmarshallerFunc(goyaml.Unmarshal)
   
   var buf bytes.Buffer
   buf.WriteString(test_data)
   
   // load yaml
   err := conf.ReadHash(&buf)
   if err != nil {
      fmt.Printf("ERROR: %s\n", err)
      return
   }
   
   // change a value
   ival := 42
   conf.Set(ival, "junk", "whatever")
   
   // write the output
   buf.Reset()
   err = conf.WriteHash(&buf)
   if err != nil {
      fmt.Printf("ERROR: %s\n", err)
      return
   }
   
   fmt.Printf("marshaled:\n%s\nEOF\n", buf.String())

}
`

**Comment by zazab** [comment]
Hi, watched the code. Problem is that yaml implementations unmarshals data to `map[inteface{}]interface{}` not `map[string]interface{}`, and zhash converts it to empty `map[string]interface{}` when you perform Set.

I'll think how to fix this
